repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.51.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shfmt
      - id: shellcheck
  - repo: local
    hooks:
      - id: lint
        name: Lints files
        entry: task lint
        files: ^.*\.sh$
        pass_filenames: false
        language: system

      - id: yaml-fmt
        name: Format YAML with prettier
        entry: task fmt:yaml
        files: ^.*\.(yaml|yml)$
        pass_filenames: false
        language: system

      - id: md-fmt
        name: Format Markdown with prettier
        entry: task fmt:md
        files: ^.*\.(MD|md)$
        pass_filenames: false
        language: system

      - id: nixpkgs-fmt
        name: Format NIX files
        entry: task fmt:nix
        files: ^.*\.nix$
        language: system
        pass_filenames: false

      - id: cfg-scripts
        name: Configure Scripts
        entry: task cfg:scripts
        files: ^.*\.sh$
        pass_filenames: false
        language: system
