---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Push stuff from local to remote
      synchronize: dest=/minecraft/ src=server/ mode=push

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /minecraft
      register: output
